export const SWITCH_HOME_TAB = 'SWITCH_HOME_TAB'
// 首页数据
export const CACHE_HOME_DATA = 'CACHE_HOME_DATA'
// 政策宣传
export const REQUEST_NOTICE_DATA = 'FETCH_NOTICE_DATA'
export const RECEIVE_NOTICE_DATA = 'RECEIVE_NOTICE_DATA'
export const UPDATE_NOTICE_DATA = 'UPDATE_NOTICE_DATA'
export const CACHE_NOTICE_DATA = 'CACHE_NOTICE_DATA'
// 办事指南
export const REQUEST_GUIDE_DATA = 'REQUEST_GUIDE_DATA'
export const RECEIVE_GUIDE_DATA = 'RECEIVE_GUIDE_DATA'
export const UPDATE_GUIDE_DATA = 'UPDATE_GUIDE_DATA'


