export const SWITCH_HOME_TAB = 'SWITCH_HOME_TAB'

export const FETCH_NOTICE_DATA = 'FETCH_NOTICE_DATA'
export const RECEIVE_NOTICE_DATA = 'RECEIVE_NOTICE_DATA'
export const CACHE_NOTICE_DATA = 'CACHE_NOTICE_DATA'

